http://localhost:3000
-ks
Content-Type: application/json; charset=utf-8
--

--
POST /api/navicore/contacts
{"first": "Liza", "last": "Artist"}
--
GET /api/navicore/contacts
--
GET /api/navicore/contacts/5ca701f0-3a83-49c0-892c-e74e61ed07f8
